// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/list-riders.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-riders.ts
var list_riders_default = defineTool({
  name: "list_riders",
  title: "List riders",
  description: "List riders in the ASTERNG fleet, optionally filtered by status or a name/phone search.",
  inputSchema: {
    status: z.enum(["active", "inactive", "suspended", "all"]).default("all").describe("Filter by rider status."),
    search: z.string().trim().optional().describe("Match against rider name or phone number."),
    limit: z.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("riders").select("id, full_name, phone_number, status, outstanding_balance, created_at").order("created_at", { ascending: false }).limit(limit);
    if (status && status !== "all") query = query.eq("status", status);
    if (search) {
      const safe = search.replace(/[,()*%]/g, " ").trim();
      if (safe) query = query.or(`full_name.ilike.%${safe}%,phone_number.ilike.%${safe}%`);
    }
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { riders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-motorcycles.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var list_motorcycles_default = defineTool2({
  name: "list_motorcycles",
  title: "List motorcycles",
  description: "List motorcycles in the ASTERNG fleet with plate number, model and assignment status.",
  inputSchema: {
    status: z2.string().trim().optional().describe("Filter by motorcycle status, e.g. available or assigned."),
    search: z2.string().trim().optional().describe("Match against plate number or model."),
    limit: z2.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("motorcycles").select("*").order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    if (search) {
      const safe = search.replace(/[,()*%]/g, " ").trim();
      if (safe) query = query.or(`plate_number.ilike.%${safe}%,model.ilike.%${safe}%`);
    }
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { motorcycles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-remittances.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var list_remittances_default = defineTool3({
  name: "list_remittances",
  title: "List remittances",
  description: "List recent rider remittance payments, optionally filtered by status or date range.",
  inputSchema: {
    status: z3.string().trim().optional().describe("Filter by remittance status, e.g. paid, pending or overdue."),
    from_date: z3.string().trim().optional().describe("Earliest remittance date (YYYY-MM-DD)."),
    to_date: z3.string().trim().optional().describe("Latest remittance date (YYYY-MM-DD)."),
    limit: z3.number().int().min(1).max(100).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("remittances").select("*").order("remittance_date", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    if (from_date) query = query.gte("remittance_date", from_date);
    if (to_date) query = query.lte("remittance_date", to_date);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { remittances: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/fleet-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var fleet_summary_default = defineTool4({
  name: "fleet_summary",
  title: "Fleet summary",
  description: "Summarise the ASTERNG fleet: rider and motorcycle counts, outstanding balances, and remittance and expense totals for a recent period.",
  inputSchema: {
    days: z4.number().int().min(1).max(365).default(30).describe("Number of past days to total remittances and expenses over.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const since = new Date(Date.now() - days * 864e5).toISOString().slice(0, 10);
    const [riders, bikes, remits, expenses] = await Promise.all([
      supabase.from("riders").select("status, outstanding_balance"),
      supabase.from("motorcycles").select("status"),
      supabase.from("remittances").select("amount").gte("remittance_date", since),
      supabase.from("expenses").select("amount").gte("expense_date", since)
    ]);
    const failure = [riders, bikes, remits, expenses].find((r) => r.error);
    if (failure?.error) return { content: [{ type: "text", text: failure.error.message }], isError: true };
    const count = (rows) => (rows ?? []).reduce((acc, row) => {
      const key = row.status ?? "unknown";
      acc[key] = (acc[key] ?? 0) + 1;
      return acc;
    }, {});
    const sum = (rows) => (rows ?? []).reduce((total, row) => total + Number(row.amount ?? 0), 0);
    const totalRemitted = sum(remits.data);
    const totalExpenses = sum(expenses.data);
    const summary = {
      period_days: days,
      riders_total: riders.data?.length ?? 0,
      riders_by_status: count(riders.data),
      outstanding_balance_total: (riders.data ?? []).reduce(
        (t, r) => t + Number(r.outstanding_balance ?? 0),
        0
      ),
      motorcycles_total: bikes.data?.length ?? 0,
      motorcycles_by_status: count(bikes.data),
      remittances_total: totalRemitted,
      expenses_total: totalExpenses,
      net_profit: totalRemitted - totalExpenses,
      currency: "NGN"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bokkpgpklwrvvvbgeewr";
var mcp_default = defineMcp({
  name: "asterng",
  title: "AsterNG",
  version: "0.1.0",
  instructions: "Tools for the ASTERNG motorcycle fleet platform. Use `list_riders`, `list_motorcycles` and `list_remittances` to read fleet records, and `fleet_summary` for totals. Amounts are Nigerian Naira (NGN). Data visibility follows the signed-in user's role.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_riders_default, list_motorcycles_default, list_remittances_default, fleet_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
